version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - npm ci
      - npx playwright install --with-deps chromium
  pre_build:
    commands:
      - npm run typecheck
  build:
    commands:
      - npm run test:smoke
      - npm run test:ci

artifacts:
  files:
    - playwright-report/**/*
    - test-results/**/*
  discard-paths: no
  name: musticker-playwright-$CODEBUILD_BUILD_NUMBER

cache:
  paths:
    - node_modules/**/*
    - /root/.cache/ms-playwright/**/*
